vpc-name      = "dove-vpc"
igw-name      = "dove-IGW"
subnet-name   = "dove-pub-subnet"
rt-name       = "dove-pub-RT"
sg-name       = "dove-sg"
instance-name = "dove-server"
key-name      = "dove-key"
iam-role      = "Devsecops-Project"
